apiVersion: v1
kind: Namespace
metadata:
  name: pod-restarter
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-restarter
  namespace: pod-restarter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-restarter
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-restarter
subjects:
- kind: ServiceAccount
  name: pod-restarter
  namespace: pod-restarter
roleRef:
  kind: ClusterRole
  name: pod-restarter
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pod-restarter
  namespace: pod-restarter
spec:
  template:
    spec:
      serviceAccountName: pod-restarter
      containers:
      - name: pod-restarter
        image: oneoneonepig/pod-restarter:0.3`
        args:
        - -namespace=default
        - -grace-period=10
        - -selector=app=nginx
      restartPolicy: Never
  backoffLimit: 3
